services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
  backend:
    container_name: backend
    build:
      context: ./backend
    depends_on:
      - db
  db:
    image: postgres:17
    container_name: db
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - /var/lib/postgresql/data
  nginx:
    build: ./nginx
    ports:
      - "3000:80"
    depends_on:
      - frontend
      - backend
