services:
  frontend:
    container_name: frontend
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
  backend:
    container_name: backend
    build: ./backend
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/.venv
  db:
    image: postgres:17
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - /var/lib/postgresql/data
  nginx:
    build: ./nginx
    ports:
      - "3000:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - frontend
      - backend
